# Generated by Django 4.2.3 on 2023-08-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='año',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='año',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='finalizada',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
    ]
